apiVersion: v1
kind: ReplicationController
metadata:
  name:  mylogin-svc
spec:
  replicas: 4
  selector:
     app:  mylogin
     version: 2.6.1
  template:
    metadata:
       labels:
          app: mylogin
          version: 2.6.1
    spec:
      containers:
      - name: mylogin-container   
        image: maha4iac/myonlinebooking:2
        ports:
         - containerPort: 8080 